// client/src/pages/Admin.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useAdminStore } from '@/stores/admin';
import type { InsertProduct, InsertCategory, OrderStatus } from '@shared/schema';
import OrderStatusBadge from '@/components/OrderStatusBadge.vue';

const adminStore = useAdminStore();
const activeTab = ref<'products' | 'orders' | 'categories'>('products');

// 상품 폼
const showProductForm = ref(false);
const productForm = ref<Partial<InsertProduct>>({
  name: '',
  slug: '',
  description: '',
  price: '',
  categoryId: '',
  imageUrl: '',
  stockQuantity: 0,
  isAvailable: true,
});
const editingProductId = ref<string | null>(null);

// 카테고리 폼
const showCategoryForm = ref(false);
const categoryForm = ref<InsertCategory>({
  name: '',
  slug: '',
  description: '',
});
const editingCategoryId = ref<string | null>(null);

// 주문 상태 업데이트
const editingOrderId = ref<string | null>(null);
const orderStatusForm = ref({ status: '', trackingNumber: '' });

onMounted(async () => {
  await Promise.all([
    adminStore.fetchAllProducts(),
    adminStore.fetchAllCategories(),
    adminStore.fetchAllOrders(),
  ]);
});

// 상품 관리
function openProductForm(productId?: string) {
  if (productId) {
    const product = adminStore.products.find(p => p.id === productId);
    if (product) {
      productForm.value = { ...product };
      editingProductId.value = productId;
    }
  } else {
    productForm.value = {
      name: '',
      slug: '',
      description: '',
      price: '',
      categoryId: '',
      imageUrl: '',
      stockQuantity: 0,
      isAvailable: true,
    };
    editingProductId.value = null;
  }
  showProductForm.value = true;
}

async function saveProduct() {
  if (editingProductId.value) {
    await adminStore.updateProduct(editingProductId.value, productForm.value);
  } else {
    await adminStore.createProduct(productForm.value as InsertProduct);
  }
  showProductForm.value = false;
  productForm.value = {};
}

async function deleteProduct(id: string) {
  if (confirm('정말 이 상품을 삭제하시겠습니까?')) {
    await adminStore.deleteProduct(id);
  }
}

// 카테고리 관리
function openCategoryForm(categoryId?: string) {
  if (categoryId) {
    const category = adminStore.categories.find(c => c.id === categoryId);
    if (category) {
      categoryForm.value = { ...category };
      editingCategoryId.value = categoryId;
    }
  } else {
    categoryForm.value = { name: '', slug: '', description: '' };
    editingCategoryId.value = null;
  }
  showCategoryForm.value = true;
}

async function saveCategory() {
  if (editingCategoryId.value) {
    await adminStore.updateCategory(editingCategoryId.value, categoryForm.value);
  } else {
    await adminStore.createCategory(categoryForm.value);
  }
  showCategoryForm.value = false;
  categoryForm.value = { name: '', slug: '', description: '' };
}

async function deleteCategory(id: string) {
  if (confirm('정말 이 카테고리를 삭제하시겠습니까?')) {
    await adminStore.deleteCategory(id);
  }
}

// 주문 관리
function openOrderStatusForm(orderId: string) {
  const order = adminStore.orders.find(o => o.id === orderId);
  if (order) {
    editingOrderId.value = orderId;
    orderStatusForm.value = {
      status: order.status,
      trackingNumber: order.trackingNumber || '',
    };
  }
}

async function updateOrderStatus() {
  if (!editingOrderId.value) return;
  
  await adminStore.updateOrderStatus(
    editingOrderId.value,
    orderStatusForm.value.status,
    orderStatusForm.value.trackingNumber || undefined
  );
  editingOrderId.value = null;
}
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="mb-8 text-3xl font-bold" data-testid="text-page-title">관리자 페이지</h1>

    <!-- 탭 -->
    <div class="mb-6 flex gap-2 border-b">
      <button
        @click="activeTab = 'products'"
        :class="[
          'px-4 py-2 font-medium transition-colors',
          activeTab === 'products'
            ? 'border-b-2 border-primary text-primary'
            : 'text-muted-foreground hover:text-foreground'
        ]"
        data-testid="tab-products"
      >
        상품 관리
      </button>
      <button
        @click="activeTab = 'orders'"
        :class="[
          'px-4 py-2 font-medium transition-colors',
          activeTab === 'orders'
            ? 'border-b-2 border-primary text-primary'
            : 'text-muted-foreground hover:text-foreground'
        ]"
        data-testid="tab-orders"
      >
        주문 관리
      </button>
      <button
        @click="activeTab = 'categories'"
        :class="[
          'px-4 py-2 font-medium transition-colors',
          activeTab === 'categories'
            ? 'border-b-2 border-primary text-primary'
            : 'text-muted-foreground hover:text-foreground'
        ]"
        data-testid="tab-categories"
      >
        카테고리 관리
      </button>
    </div>

    <!-- 상품 관리 -->
    <div v-if="activeTab === 'products'" class="space-y-4">
      <div class="flex justify-between items-center">
        <h2 class="text-2xl font-bold">상품 목록</h2>
        <button
          @click="openProductForm()"
          class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          data-testid="button-add-product"
        >
          + 상품 추가
        </button>
      </div>

      <div class="rounded-lg border bg-card overflow-hidden">
        <table class="w-full">
          <thead class="bg-muted">
            <tr>
              <th class="px-4 py-3 text-left text-sm font-medium">상품명</th>
              <th class="px-4 py-3 text-left text-sm font-medium">가격</th>
              <th class="px-4 py-3 text-left text-sm font-medium">재고</th>
              <th class="px-4 py-3 text-left text-sm font-medium">상태</th>
              <th class="px-4 py-3 text-right text-sm font-medium">관리</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="product in adminStore.products"
              :key="product.id"
              class="border-t hover:bg-muted/50"
              :data-testid="`product-row-${product.id}`"
            >
              <td class="px-4 py-3">{{ product.name }}</td>
              <td class="px-4 py-3">{{ parseFloat(product.price).toLocaleString() }}원</td>
              <td class="px-4 py-3">{{ product.stockQuantity }}</td>
              <td class="px-4 py-3">
                <span :class="product.isAvailable ? 'text-green-600' : 'text-red-600'">
                  {{ product.isAvailable ? '판매중' : '판매중지' }}
                </span>
              </td>
              <td class="px-4 py-3 text-right">
                <button
                  @click="openProductForm(product.id)"
                  class="mr-2 text-sm text-primary hover:underline"
                  :data-testid="`button-edit-product-${product.id}`"
                >
                  수정
                </button>
                <button
                  @click="deleteProduct(product.id)"
                  class="text-sm text-destructive hover:underline"
                  :data-testid="`button-delete-product-${product.id}`"
                >
                  삭제
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- 상품 폼 모달 -->
      <div v-if="showProductForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
        <div class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-lg bg-background p-6">
          <h3 class="mb-4 text-xl font-bold">
            {{ editingProductId ? '상품 수정' : '상품 추가' }}
          </h3>
          <form @submit.prevent="saveProduct" class="space-y-4">
            <div>
              <label class="mb-1 block text-sm font-medium">상품명</label>
              <input
                v-model="productForm.name"
                required
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-product-name"
              />
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">Slug</label>
              <input
                v-model="productForm.slug"
                required
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-product-slug"
              />
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">설명</label>
              <textarea
                v-model="productForm.description"
                rows="3"
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-product-description"
              ></textarea>
            </div>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="mb-1 block text-sm font-medium">가격</label>
                <input
                  v-model="productForm.price"
                  type="number"
                  required
                  class="w-full rounded-lg border px-3 py-2"
                  data-testid="input-product-price"
                />
              </div>
              <div>
                <label class="mb-1 block text-sm font-medium">재고</label>
                <input
                  v-model="productForm.stockQuantity"
                  type="number"
                  class="w-full rounded-lg border px-3 py-2"
                  data-testid="input-product-stock"
                />
              </div>
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">카테고리</label>
              <select
                v-model="productForm.categoryId"
                class="w-full rounded-lg border px-3 py-2"
                data-testid="select-product-category"
              >
                <option value="">선택 안함</option>
                <option v-for="cat in adminStore.categories" :key="cat.id" :value="cat.id">
                  {{ cat.name }}
                </option>
              </select>
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">이미지 URL</label>
              <input
                v-model="productForm.imageUrl"
                type="url"
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-product-image"
              />
            </div>
            <div class="flex items-center gap-2">
              <input
                v-model="productForm.isAvailable"
                type="checkbox"
                id="product-available"
                data-testid="checkbox-product-available"
              />
              <label for="product-available" class="text-sm font-medium">판매 가능</label>
            </div>
            <div class="flex gap-2 justify-end">
              <button
                type="button"
                @click="showProductForm = false"
                class="rounded-lg border px-4 py-2"
                data-testid="button-cancel-product"
              >
                취소
              </button>
              <button
                type="submit"
                class="rounded-lg bg-primary px-4 py-2 text-primary-foreground"
                data-testid="button-save-product"
              >
                저장
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- 주문 관리 -->
    <div v-else-if="activeTab === 'orders'" class="space-y-4">
      <h2 class="text-2xl font-bold">주문 목록</h2>

      <div class="rounded-lg border bg-card overflow-hidden">
        <table class="w-full">
          <thead class="bg-muted">
            <tr>
              <th class="px-4 py-3 text-left text-sm font-medium">주문번호</th>
              <th class="px-4 py-3 text-left text-sm font-medium">받는 분</th>
              <th class="px-4 py-3 text-left text-sm font-medium">금액</th>
              <th class="px-4 py-3 text-left text-sm font-medium">상태</th>
              <th class="px-4 py-3 text-right text-sm font-medium">관리</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="order in adminStore.orders"
              :key="order.id"
              class="border-t hover:bg-muted/50"
              :data-testid="`order-row-${order.id}`"
            >
              <td class="px-4 py-3">{{ order.id.substring(0, 8) }}</td>
              <td class="px-4 py-3">{{ order.shippingName }}</td>
              <td class="px-4 py-3">{{ parseFloat(order.totalAmount).toLocaleString() }}원</td>
              <td class="px-4 py-3">
                <OrderStatusBadge :status="order.status as OrderStatus" />
              </td>
              <td class="px-4 py-3 text-right">
                <button
                  @click="openOrderStatusForm(order.id)"
                  class="text-sm text-primary hover:underline"
                  :data-testid="`button-edit-order-${order.id}`"
                >
                  상태 변경
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- 주문 상태 변경 모달 -->
      <div v-if="editingOrderId" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
        <div class="w-full max-w-md rounded-lg bg-background p-6">
          <h3 class="mb-4 text-xl font-bold">주문 상태 변경</h3>
          <form @submit.prevent="updateOrderStatus" class="space-y-4">
            <div>
              <label class="mb-1 block text-sm font-medium">주문 상태</label>
              <select
                v-model="orderStatusForm.status"
                required
                class="w-full rounded-lg border px-3 py-2"
                data-testid="select-order-status"
              >
                <option value="pending_payment">결제 대기</option>
                <option value="payment_confirmed">결제 완료</option>
                <option value="preparing">상품 준비 중</option>
                <option value="shipped">배송 중</option>
                <option value="delivered">배송 완료</option>
                <option value="cancelled">취소됨</option>
              </select>
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">운송장 번호</label>
              <input
                v-model="orderStatusForm.trackingNumber"
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-tracking-number"
              />
            </div>
            <div class="flex gap-2 justify-end">
              <button
                type="button"
                @click="editingOrderId = null"
                class="rounded-lg border px-4 py-2"
                data-testid="button-cancel-order"
              >
                취소
              </button>
              <button
                type="submit"
                class="rounded-lg bg-primary px-4 py-2 text-primary-foreground"
                data-testid="button-save-order"
              >
                저장
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- 카테고리 관리 -->
    <div v-else-if="activeTab === 'categories'" class="space-y-4">
      <div class="flex justify-between items-center">
        <h2 class="text-2xl font-bold">카테고리 목록</h2>
        <button
          @click="openCategoryForm()"
          class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          data-testid="button-add-category"
        >
          + 카테고리 추가
        </button>
      </div>

      <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <div
          v-for="category in adminStore.categories"
          :key="category.id"
          class="rounded-lg border bg-card p-4"
          :data-testid="`category-card-${category.id}`"
        >
          <h3 class="mb-2 text-lg font-semibold">{{ category.name }}</h3>
          <p class="mb-4 text-sm text-muted-foreground">{{ category.description || '설명 없음' }}</p>
          <div class="flex gap-2">
            <button
              @click="openCategoryForm(category.id)"
              class="text-sm text-primary hover:underline"
              :data-testid="`button-edit-category-${category.id}`"
            >
              수정
            </button>
            <button
              @click="deleteCategory(category.id)"
              class="text-sm text-destructive hover:underline"
              :data-testid="`button-delete-category-${category.id}`"
            >
              삭제
            </button>
          </div>
        </div>
      </div>

      <!-- 카테고리 폼 모달 -->
      <div v-if="showCategoryForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
        <div class="w-full max-w-md rounded-lg bg-background p-6">
          <h3 class="mb-4 text-xl font-bold">
            {{ editingCategoryId ? '카테고리 수정' : '카테고리 추가' }}
          </h3>
          <form @submit.prevent="saveCategory" class="space-y-4">
            <div>
              <label class="mb-1 block text-sm font-medium">카테고리명</label>
              <input
                v-model="categoryForm.name"
                required
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-category-name"
              />
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">Slug</label>
              <input
                v-model="categoryForm.slug"
                required
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-category-slug"
              />
            </div>
            <div>
              <label class="mb-1 block text-sm font-medium">설명</label>
              <textarea
                v-model="categoryForm.description"
                rows="3"
                class="w-full rounded-lg border px-3 py-2"
                data-testid="input-category-description"
              ></textarea>
            </div>
            <div class="flex gap-2 justify-end">
              <button
                type="button"
                @click="showCategoryForm = false"
                class="rounded-lg border px-4 py-2"
                data-testid="button-cancel-category"
              >
                취소
              </button>
              <button
                type="submit"
                class="rounded-lg bg-primary px-4 py-2 text-primary-foreground"
                data-testid="button-save-category"
              >
                저장
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

// client/src/pages/Admin.tsx
import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Plus, Edit, Trash2, Package, ShoppingCart, Tag } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { useAuth } from "@/hooks/useAuth";
import type { Product, Category, Order } from "@shared/schema";

const statusConfig = {
  pending_payment: { label: "입금 대기" },
  payment_confirmed: { label: "결제 확인" },
  preparing: { label: "배송 준비" },
  shipped: { label: "배송 중" },
  delivered: { label: "배송 완료" },
  cancelled: { label: "주문 취소" },
};

export default function Admin() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { isAdmin, isLoading: authLoading } = useAuth();
  const [activeTab, setActiveTab] = useState("products");

  useEffect(() => {
    if (!authLoading && !isAdmin) {
      window.location.href = "/";
    }
  }, [isAdmin, authLoading]);

  if (authLoading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="animate-pulse">
            <div className="h-8 bg-muted rounded w-48 mb-4" />
            <div className="h-64 bg-muted rounded" />
          </div>
        </div>
      </div>
    );
  }

  if (!isAdmin) {
    return null;
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <h1 className="text-3xl md:text-4xl font-bold mb-8" data-testid="text-page-title">
          관리자 대시보드
        </h1>

        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-3 mb-8">
            <TabsTrigger value="products" data-testid="tab-products">
              <Package className="h-4 w-4 mr-2" />
              상품 관리
            </TabsTrigger>
            <TabsTrigger value="orders" data-testid="tab-orders">
              <ShoppingCart className="h-4 w-4 mr-2" />
              주문 관리
            </TabsTrigger>
            <TabsTrigger value="categories" data-testid="tab-categories">
              <Tag className="h-4 w-4 mr-2" />
              카테고리 관리
            </TabsTrigger>
          </TabsList>

          <TabsContent value="products">
            <ProductsManagement />
          </TabsContent>

          <TabsContent value="orders">
            <OrdersManagement />
          </TabsContent>

          <TabsContent value="categories">
            <CategoriesManagement />
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}

function ProductsManagement() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);

  const { data: products = [] } = useQuery<Product[]>({
    queryKey: ["/api/admin/products"],
  });

  const { data: categories = [] } = useQuery<Category[]>({
    queryKey: ["/api/categories"],
  });

  const deleteProduct = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest("DELETE", `/api/admin/products/${id}`, {});
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/products"] });
      queryClient.invalidateQueries({ queryKey: ["/api/products"] });
      toast({ title: "상품이 삭제되었습니다" });
    },
  });

  const handleEdit = (product: Product) => {
    setEditingProduct(product);
    setIsDialogOpen(true);
  };

  const handleAdd = () => {
    setEditingProduct(null);
    setIsDialogOpen(true);
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold">상품 목록</h2>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button onClick={handleAdd} data-testid="button-add-product">
              <Plus className="h-4 w-4 mr-2" />
              상품 추가
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <ProductForm
              product={editingProduct}
              categories={categories}
              onSuccess={() => {
                setIsDialogOpen(false);
                setEditingProduct(null);
              }}
            />
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid gap-4">
        {products.map((product) => (
          <Card key={product.id} data-testid={`product-card-${product.id}`}>
            <CardContent className="p-4">
              <div className="flex gap-4">
                <div className="w-24 h-24 bg-muted rounded overflow-hidden flex-shrink-0">
                  {product.imageUrl && (
                    <img
                      src={product.imageUrl}
                      alt={product.name}
                      className="h-full w-full object-cover"
                    />
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="font-medium text-lg mb-2" data-testid={`text-product-name-${product.id}`}>
                    {product.name}
                  </h3>
                  <p className="text-sm text-muted-foreground mb-2">{product.description}</p>
                  <div className="flex items-center gap-4 flex-wrap">
                    <span className="font-bold text-primary">₩{parseInt(product.price).toLocaleString()}</span>
                    <Badge variant="secondary" data-testid={`badge-stock-${product.id}`}>
                      재고: {product.stockQuantity}
                    </Badge>
                    <Badge variant={product.isAvailable ? "default" : "destructive"}>
                      {product.isAvailable ? "판매중" : "품절"}
                    </Badge>
                  </div>
                </div>
                <div className="flex flex-col gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleEdit(product)}
                    data-testid={`button-edit-${product.id}`}
                  >
                    <Edit className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => deleteProduct.mutate(product.id)}
                    data-testid={`button-delete-${product.id}`}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

function ProductForm({
  product,
  categories,
  onSuccess,
}: {
  product: Product | null;
  categories: Category[];
  onSuccess: () => void;
}) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState({
    name: product?.name || "",
    slug: product?.slug || "",
    description: product?.description || "",
    price: product?.price || "",
    originalPrice: product?.originalPrice || "",
    categoryId: product?.categoryId || "",
    imageUrl: product?.imageUrl || "",
    stockQuantity: product?.stockQuantity || 0,
    isAvailable: product?.isAvailable ?? true,
  });

  const saveProduct = useMutation({
    mutationFn: async () => {
      if (product) {
        await apiRequest("PATCH", `/api/admin/products/${product.id}`, formData);
      } else {
        await apiRequest("POST", "/api/admin/products", formData);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/products"] });
      queryClient.invalidateQueries({ queryKey: ["/api/products"] });
      toast({ title: product ? "상품이 수정되었습니다" : "상품이 추가되었습니다" });
      onSuccess();
    },
    onError: (error: Error) => {
      toast({ title: "오류", description: error.message, variant: "destructive" });
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    saveProduct.mutate();
  };

  return (
    <form onSubmit={handleSubmit}>
      <DialogHeader>
        <DialogTitle>{product ? "상품 수정" : "상품 추가"}</DialogTitle>
      </DialogHeader>
      <div className="space-y-4 mt-4">
        <div>
          <Label htmlFor="name">상품명 *</Label>
          <Input
            id="name"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            required
            data-testid="input-product-name"
          />
        </div>
        <div>
          <Label htmlFor="slug">URL 슬러그 *</Label>
          <Input
            id="slug"
            value={formData.slug}
            onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
            placeholder="product-name"
            required
            data-testid="input-product-slug"
          />
        </div>
        <div>
          <Label htmlFor="description">설명</Label>
          <Textarea
            id="description"
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            rows={3}
            data-testid="input-product-description"
          />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <Label htmlFor="price">판매가 *</Label>
            <Input
              id="price"
              type="number"
              step="0.01"
              value={formData.price}
              onChange={(e) => setFormData({ ...formData, price: e.target.value })}
              required
              data-testid="input-product-price"
            />
          </div>
          <div>
            <Label htmlFor="originalPrice">정가</Label>
            <Input
              id="originalPrice"
              type="number"
              step="0.01"
              value={formData.originalPrice}
              onChange={(e) => setFormData({ ...formData, originalPrice: e.target.value })}
              data-testid="input-product-original-price"
            />
          </div>
        </div>
        <div>
          <Label htmlFor="category">카테고리</Label>
          <Select
            value={formData.categoryId}
            onValueChange={(value) => setFormData({ ...formData, categoryId: value })}
          >
            <SelectTrigger data-testid="select-category">
              <SelectValue placeholder="카테고리 선택" />
            </SelectTrigger>
            <SelectContent>
              {categories.map((cat) => (
                <SelectItem key={cat.id} value={cat.id}>
                  {cat.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div>
          <Label htmlFor="imageUrl">이미지 URL</Label>
          <Input
            id="imageUrl"
            value={formData.imageUrl}
            onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })}
            placeholder="https://..."
            data-testid="input-product-image-url"
          />
        </div>
        <div>
          <Label htmlFor="stockQuantity">재고 수량 *</Label>
          <Input
            id="stockQuantity"
            type="number"
            value={formData.stockQuantity}
            onChange={(e) => setFormData({ ...formData, stockQuantity: parseInt(e.target.value) || 0 })}
            required
            data-testid="input-product-stock"
          />
        </div>
        <div className="flex items-center gap-2">
          <input
            type="checkbox"
            id="isAvailable"
            checked={formData.isAvailable}
            onChange={(e) => setFormData({ ...formData, isAvailable: e.target.checked })}
            className="h-4 w-4"
            data-testid="checkbox-product-available"
          />
          <Label htmlFor="isAvailable" className="cursor-pointer">판매 가능</Label>
        </div>
        <Button type="submit" className="w-full" disabled={saveProduct.isPending} data-testid="button-save-product">
          {saveProduct.isPending ? "저장 중..." : product ? "수정하기" : "추가하기"}
        </Button>
      </div>
    </form>
  );
}

function OrdersManagement() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: orders = [] } = useQuery<Order[]>({
    queryKey: ["/api/admin/orders"],
  });

  const updateOrderStatus = useMutation({
    mutationFn: async ({ orderId, status, trackingNumber }: { orderId: string; status: string; trackingNumber?: string }) => {
      await apiRequest("PATCH", `/api/admin/orders/${orderId}`, { status, trackingNumber });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/orders"] });
      toast({ title: "주문 상태가 업데이트되었습니다" });
    },
  });

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">주문 목록</h2>
      <div className="grid gap-4">
        {orders.map((order) => (
          <Card key={order.id} data-testid={`order-card-${order.id}`}>
            <CardContent className="p-4">
              <div className="space-y-4">
                <div className="flex justify-between items-start">
                  <div>
                    <p className="font-medium">주문번호: {order.id.slice(0, 13)}...</p>
                    <p className="text-sm text-muted-foreground">
                      {new Date(order.createdAt).toLocaleString('ko-KR')}
                    </p>
                    <p className="text-sm">받는 사람: {order.shippingName}</p>
                    <p className="text-sm">연락처: {order.shippingPhone}</p>
                  </div>
                  <p className="text-lg font-bold text-primary">
                    ₩{parseInt(order.totalAmount).toLocaleString()}
                  </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <Label htmlFor={`status-${order.id}`}>주문 상태</Label>
                    <Select
                      value={order.status}
                      onValueChange={(value) =>
                        updateOrderStatus.mutate({ orderId: order.id, status: value })
                      }
                    >
                      <SelectTrigger id={`status-${order.id}`} data-testid={`select-status-${order.id}`}>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {Object.entries(statusConfig).map(([value, config]) => (
                          <SelectItem key={value} value={value}>
                            {config.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="md:col-span-2">
                    <Label htmlFor={`tracking-${order.id}`}>운송장 번호</Label>
                    <div className="flex gap-2">
                      <Input
                        id={`tracking-${order.id}`}
                        defaultValue={order.trackingNumber || ""}
                        placeholder="운송장 번호 입력"
                        data-testid={`input-tracking-${order.id}`}
                        onBlur={(e) => {
                          if (e.target.value !== order.trackingNumber) {
                            updateOrderStatus.mutate({
                              orderId: order.id,
                              status: order.status,
                              trackingNumber: e.target.value,
                            });
                          }
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

function CategoriesManagement() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<Category | null>(null);

  const { data: categories = [] } = useQuery<Category[]>({
    queryKey: ["/api/categories"],
  });

  const deleteCategory = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest("DELETE", `/api/admin/categories/${id}`, {});
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/categories"] });
      toast({ title: "카테고리가 삭제되었습니다" });
    },
  });

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold">카테고리 목록</h2>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button onClick={() => { setEditingCategory(null); setIsDialogOpen(true); }} data-testid="button-add-category">
              <Plus className="h-4 w-4 mr-2" />
              카테고리 추가
            </Button>
          </DialogTrigger>
          <DialogContent>
            <CategoryForm
              category={editingCategory}
              onSuccess={() => {
                setIsDialogOpen(false);
                setEditingCategory(null);
              }}
            />
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {categories.map((category) => (
          <Card key={category.id} data-testid={`category-card-${category.id}`}>
            <CardHeader>
              <CardTitle>{category.name}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground mb-4">{category.description}</p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    setEditingCategory(category);
                    setIsDialogOpen(true);
                  }}
                  data-testid={`button-edit-category-${category.id}`}
                >
                  <Edit className="h-4 w-4 mr-2" />
                  수정
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => deleteCategory.mutate(category.id)}
                  data-testid={`button-delete-category-${category.id}`}
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  삭제
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

function CategoryForm({
  category,
  onSuccess,
}: {
  category: Category | null;
  onSuccess: () => void;
}) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState({
    name: category?.name || "",
    slug: category?.slug || "",
    description: category?.description || "",
  });

  const saveCategory = useMutation({
    mutationFn: async () => {
      if (category) {
        await apiRequest("PATCH", `/api/admin/categories/${category.id}`, formData);
      } else {
        await apiRequest("POST", "/api/admin/categories", formData);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/categories"] });
      toast({ title: category ? "카테고리가 수정되었습니다" : "카테고리가 추가되었습니다" });
      onSuccess();
    },
  });

  return (
    <form onSubmit={(e) => { e.preventDefault(); saveCategory.mutate(); }}>
      <DialogHeader>
        <DialogTitle>{category ? "카테고리 수정" : "카테고리 추가"}</DialogTitle>
      </DialogHeader>
      <div className="space-y-4 mt-4">
        <div>
          <Label htmlFor="cat-name">카테고리명 *</Label>
          <Input
            id="cat-name"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            required
            data-testid="input-category-name"
          />
        </div>
        <div>
          <Label htmlFor="cat-slug">URL 슬러그 *</Label>
          <Input
            id="cat-slug"
            value={formData.slug}
            onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
            required
            data-testid="input-category-slug"
          />
        </div>
        <div>
          <Label htmlFor="cat-desc">설명</Label>
          <Textarea
            id="cat-desc"
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            data-testid="input-category-description"
          />
        </div>
        <Button type="submit" className="w-full" disabled={saveCategory.isPending} data-testid="button-save-category">
          {saveCategory.isPending ? "저장 중..." : category ? "수정하기" : "추가하기"}
        </Button>
      </div>
    </form>
  );
}
