// client/src/pages/Cart.tsx
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Minus, Plus, Trash2, ShoppingBag } from "lucide-react";
import { Link } from "wouter";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import type { CartItem, Product } from "@shared/schema";

type CartItemWithProduct = CartItem & { product: Product };

export default function Cart() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: cartItems = [], isLoading } = useQuery<CartItemWithProduct[]>({
    queryKey: ["/api/cart"],
  });

  const updateQuantity = useMutation({
    mutationFn: async ({ itemId, quantity }: { itemId: string; quantity: number }) => {
      await apiRequest("PATCH", `/api/cart/${itemId}`, { quantity });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/cart"] });
    },
    onError: (error: Error) => {
      toast({
        title: "오류",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const removeItem = useMutation({
    mutationFn: async (itemId: string) => {
      await apiRequest("DELETE", `/api/cart/${itemId}`, {});
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/cart"] });
      toast({
        title: "상품이 삭제되었습니다",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "오류",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const totalAmount = cartItems.reduce(
    (sum, item) => sum + parseFloat(item.product.price) * item.quantity,
    0
  );

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="animate-pulse space-y-4">
            <div className="h-8 bg-muted rounded w-48" />
            <div className="h-32 bg-muted rounded" />
            <div className="h-32 bg-muted rounded" />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <h1 className="text-3xl md:text-4xl font-bold mb-8" data-testid="text-page-title">
          장바구니
        </h1>

        {cartItems.length === 0 ? (
          <Card className="text-center py-16" data-testid="empty-cart">
            <CardContent className="space-y-4">
              <ShoppingBag className="h-16 w-16 mx-auto text-muted-foreground" />
              <p className="text-lg text-muted-foreground">장바구니가 비어있습니다</p>
              <Link href="/">
                <Button data-testid="button-continue-shopping">
                  쇼핑 계속하기
                </Button>
              </Link>
            </CardContent>
          </Card>
        ) : (
          <div className="grid lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 space-y-4">
              {cartItems.map((item) => (
                <Card key={item.id} data-testid={`cart-item-${item.id}`}>
                  <CardContent className="p-4 md:p-6">
                    <div className="flex gap-4">
                      <div className="w-24 h-24 md:w-32 md:h-32 flex-shrink-0 bg-muted rounded-lg overflow-hidden">
                        {item.product.imageUrl ? (
                          <img
                            src={item.product.imageUrl}
                            alt={item.product.name}
                            className="h-full w-full object-cover"
                            data-testid={`img-cart-item-${item.id}`}
                          />
                        ) : (
                          <div className="flex h-full items-center justify-center">
                            <ShoppingBag className="h-12 w-12 text-muted-foreground" />
                          </div>
                        )}
                      </div>

                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium text-base md:text-lg mb-2" data-testid={`text-item-name-${item.id}`}>
                          {item.product.name}
                        </h3>
                        <p className="text-lg font-bold text-primary mb-4" data-testid={`text-item-price-${item.id}`}>
                          ₩{parseInt(item.product.price).toLocaleString()}
                        </p>

                        <div className="flex items-center gap-4 flex-wrap">
                          <div className="flex items-center gap-2">
                            <Button
                              variant="outline"
                              size="icon"
                              className="h-8 w-8"
                              onClick={() =>
                                updateQuantity.mutate({
                                  itemId: item.id,
                                  quantity: Math.max(1, item.quantity - 1),
                                })
                              }
                              disabled={item.quantity <= 1}
                              data-testid={`button-decrease-${item.id}`}
                            >
                              <Minus className="h-4 w-4" />
                            </Button>
                            <Input
                              type="number"
                              min="1"
                              max={item.product.stockQuantity}
                              value={item.quantity}
                              onChange={(e) => {
                                const qty = parseInt(e.target.value) || 1;
                                updateQuantity.mutate({ itemId: item.id, quantity: qty });
                              }}
                              className="w-16 text-center h-8"
                              data-testid={`input-quantity-${item.id}`}
                            />
                            <Button
                              variant="outline"
                              size="icon"
                              className="h-8 w-8"
                              onClick={() =>
                                updateQuantity.mutate({
                                  itemId: item.id,
                                  quantity: Math.min(item.product.stockQuantity, item.quantity + 1),
                                })
                              }
                              disabled={item.quantity >= item.product.stockQuantity}
                              data-testid={`button-increase-${item.id}`}
                            >
                              <Plus className="h-4 w-4" />
                            </Button>
                          </div>

                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => removeItem.mutate(item.id)}
                            className="text-destructive hover:text-destructive"
                            data-testid={`button-remove-${item.id}`}
                          >
                            <Trash2 className="h-4 w-4 mr-2" />
                            삭제
                          </Button>
                        </div>
                      </div>

                      <div className="text-right hidden md:block">
                        <p className="text-lg font-bold" data-testid={`text-item-total-${item.id}`}>
                          ₩{(parseFloat(item.product.price) * item.quantity).toLocaleString()}
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>

            <div className="lg:col-span-1">
              <Card className="sticky top-24">
                <CardHeader>
                  <CardTitle>주문 요약</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex justify-between text-base">
                    <span>상품 개수:</span>
                    <span data-testid="text-item-count">{cartItems.length}개</span>
                  </div>
                  <div className="flex justify-between text-base">
                    <span>총 수량:</span>
                    <span data-testid="text-total-quantity">
                      {cartItems.reduce((sum, item) => sum + item.quantity, 0)}개
                    </span>
                  </div>
                  <div className="border-t pt-4">
                    <div className="flex justify-between text-xl font-bold mb-6">
                      <span>총 금액:</span>
                      <span className="text-primary" data-testid="text-total-amount">
                        ₩{totalAmount.toLocaleString()}
                      </span>
                    </div>
                    <Link href="/checkout">
                      <Button className="w-full" size="lg" data-testid="button-checkout">
                        결제하기
                      </Button>
                    </Link>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// client/src/pages/Cart.vue
<script setup lang="ts">
import { onMounted, computed } from 'vue';
import { useRouter } from 'vue-router';
import { useCartStore } from '@/stores/cart';
import EmptyState from '@/components/EmptyState.vue';

const router = useRouter();
const cartStore = useCartStore();

const subtotal = computed(() => cartStore.totalPrice);

onMounted(async () => {
  await cartStore.fetchCart();
});

async function handleQuantityChange(itemId: string, newQuantity: number) {
  if (newQuantity < 1) return;
  await cartStore.updateQuantity(itemId, newQuantity);
}

async function handleRemoveItem(itemId: string) {
  if (confirm('이 상품을 장바구니에서 제거하시겠습니까?')) {
    await cartStore.removeItem(itemId);
  }
}

function goToCheckout() {
  router.push('/checkout');
}
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <h1 class="mb-8 text-3xl font-bold" data-testid="text-page-title">장바구니</h1>

    <!-- 로딩 -->
    <div v-if="cartStore.loading" class="flex justify-center py-12">
      <div class="text-center">
        <div class="mb-2 text-4xl">⏳</div>
        <p class="text-muted-foreground">장바구니를 불러오는 중...</p>
      </div>
    </div>

    <!-- 빈 장바구니 -->
    <EmptyState
      v-else-if="cartStore.isEmpty"
      title="장바구니가 비어있습니다"
      description="상품을 장바구니에 담아보세요."
      action-text="쇼핑 계속하기"
      action-to="/"
    />

    <!-- 장바구니 아이템 -->
    <div v-else class="grid gap-8 lg:grid-cols-3">
      <!-- 아이템 목록 -->
      <div class="space-y-4 lg:col-span-2">
        <div
          v-for="item in cartStore.items"
          :key="item.id"
          class="flex gap-4 rounded-lg border bg-card p-4"
          :data-testid="`cart-item-${item.id}`"
        >
          <!-- 상품 이미지 -->
          <div class="h-24 w-24 flex-shrink-0 overflow-hidden rounded-lg bg-muted">
            <img
              v-if="item.product.imageUrl"
              :src="item.product.imageUrl"
              :alt="item.product.name"
              class="h-full w-full object-cover"
            />
            <div v-else class="flex h-full w-full items-center justify-center text-muted-foreground text-xs">
              이미지 없음
            </div>
          </div>

          <!-- 상품 정보 -->
          <div class="flex flex-1 flex-col justify-between">
            <div>
              <h3 class="font-medium" :data-testid="`text-item-name-${item.id}`">
                {{ item.product.name }}
              </h3>
              <p class="mt-1 text-sm text-primary font-semibold" :data-testid="`text-item-price-${item.id}`">
                {{ parseFloat(item.product.price).toLocaleString() }}원
              </p>
            </div>

            <!-- 수량 조절 및 삭제 -->
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2">
                <button
                  @click="handleQuantityChange(item.id, item.quantity - 1)"
                  :disabled="item.quantity <= 1"
                  class="h-8 w-8 rounded-md border bg-background text-foreground hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50"
                  :data-testid="`button-decrease-${item.id}`"
                >
                  -
                </button>
                <span class="w-12 text-center" :data-testid="`text-quantity-${item.id}`">
                  {{ item.quantity }}
                </span>
                <button
                  @click="handleQuantityChange(item.id, item.quantity + 1)"
                  class="h-8 w-8 rounded-md border bg-background text-foreground hover:bg-muted"
                  :data-testid="`button-increase-${item.id}`"
                >
                  +
                </button>
              </div>

              <button
                @click="handleRemoveItem(item.id)"
                class="text-sm text-destructive hover:underline"
                :data-testid="`button-remove-${item.id}`"
              >
                삭제
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- 주문 요약 -->
      <div class="lg:col-span-1">
        <div class="sticky top-20 rounded-lg border bg-card p-6 space-y-4">
          <h2 class="text-xl font-bold">주문 요약</h2>

          <div class="space-y-2 border-t pt-4">
            <div class="flex justify-between text-sm">
              <span class="text-muted-foreground">상품 개수</span>
              <span data-testid="text-total-items">{{ cartStore.totalItems }}개</span>
            </div>
            <div class="flex justify-between">
              <span class="font-semibold">총 금액</span>
              <span class="text-xl font-bold text-primary" data-testid="text-subtotal">
                {{ subtotal.toLocaleString() }}원
              </span>
            </div>
          </div>

          <button
            @click="goToCheckout"
            class="w-full rounded-lg bg-primary px-6 py-3 font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
            data-testid="button-checkout"
          >
            주문하기
          </button>

          <router-link
            to="/"
            class="block text-center text-sm text-primary hover:underline"
            data-testid="link-continue-shopping"
          >
            쇼핑 계속하기
          </router-link>
        </div>
      </div>
    </div>
  </div>
</template>
