// client/src/pages/Home.vue
<script setup lang="ts">
import { onMounted, computed } from 'vue';
import { useProductsStore } from '@/stores/products';
import ProductCard from '@/components/ProductCard.vue';
import EmptyState from '@/components/EmptyState.vue';

const productsStore = useProductsStore();

const hasFilters = computed(() => 
  productsStore.searchQuery || productsStore.selectedCategoryId
);

onMounted(async () => {
  await Promise.all([
    productsStore.fetchProducts(),
    productsStore.fetchCategories(),
  ]);
});

async function handleSearch(e: Event) {
  const target = e.target as HTMLInputElement;
  productsStore.setSearchQuery(target.value);
  await productsStore.fetchProducts();
}

async function handleCategoryChange(categoryId: string | null) {
  productsStore.setSelectedCategory(categoryId);
  await productsStore.fetchProducts();
}

async function handleClearFilters() {
  productsStore.clearFilters();
  await productsStore.fetchProducts();
}
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <!-- 검색 및 필터 -->
    <div class="mb-8 space-y-4">
      <h1 class="text-3xl font-bold" data-testid="text-page-title">상품 목록</h1>
      
      <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <!-- 검색 -->
        <input
          type="text"
          :value="productsStore.searchQuery"
          @input="handleSearch"
          placeholder="상품 검색..."
          class="w-full rounded-lg border border-input bg-background px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary md:w-80"
          data-testid="input-search"
        />

        <!-- 카테고리 필터 -->
        <div class="flex flex-wrap items-center gap-2">
          <button
            @click="handleCategoryChange(null)"
            :class="[
              'rounded-full px-4 py-2 text-sm font-medium transition-colors',
              !productsStore.selectedCategoryId
                ? 'bg-primary text-primary-foreground'
                : 'bg-muted text-muted-foreground hover:bg-muted/80'
            ]"
            data-testid="button-category-all"
          >
            전체
          </button>
          <button
            v-for="category in productsStore.categories"
            :key="category.id"
            @click="handleCategoryChange(category.id)"
            :class="[
              'rounded-full px-4 py-2 text-sm font-medium transition-colors',
              productsStore.selectedCategoryId === category.id
                ? 'bg-primary text-primary-foreground'
                : 'bg-muted text-muted-foreground hover:bg-muted/80'
            ]"
            :data-testid="`button-category-${category.id}`"
          >
            {{ category.name }}
          </button>
        </div>
      </div>

      <!-- 필터 초기화 -->
      <div v-if="hasFilters" class="flex items-center gap-2">
        <span class="text-sm text-muted-foreground">
          {{ productsStore.filteredProducts.length }}개 상품
        </span>
        <button
          @click="handleClearFilters"
          class="text-sm text-primary hover:underline"
          data-testid="button-clear-filters"
        >
          필터 초기화
        </button>
      </div>
    </div>

    <!-- 로딩 -->
    <div v-if="productsStore.loading" class="flex justify-center py-12">
      <div class="text-center">
        <div class="mb-2 text-4xl">⏳</div>
        <p class="text-muted-foreground">상품을 불러오는 중...</p>
      </div>
    </div>

    <!-- 에러 -->
    <div v-else-if="productsStore.error" class="rounded-lg border border-destructive bg-destructive/10 p-4">
      <p class="text-destructive" data-testid="text-error">
        {{ productsStore.error }}
      </p>
    </div>

    <!-- 상품 목록 -->
    <div v-else-if="productsStore.filteredProducts.length > 0">
      <div class="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
        <ProductCard 
          v-for="product in productsStore.filteredProducts" 
          :key="product.id" 
          :product="product" 
        />
      </div>
    </div>

    <!-- 빈 상태 -->
    <EmptyState
      v-else
      title="상품이 없습니다"
      description="검색 조건을 변경하거나 필터를 초기화해보세요."
      :action-text="hasFilters ? '필터 초기화' : undefined"
      @action="handleClearFilters"
    />
  </div>
</template>

// client/src/pages/Home.tsx
import { useState, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { Navbar } from "@/components/Navbar";
import { ProductCard } from "@/components/ProductCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Search, Filter } from "lucide-react";
import type { Product, Category } from "@shared/schema";

export default function Home() {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [localSearchQuery, setLocalSearchQuery] = useState("");

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const search = params.get("search");
    if (search) {
      setSearchQuery(search);
      setLocalSearchQuery(search);
    }
  }, []);

  const { data: categories = [] } = useQuery<Category[]>({
    queryKey: ["/api/categories"],
  });

  const { data: products = [], isLoading } = useQuery<Product[]>({
    queryKey: ["/api/products", { search: searchQuery, categoryId: selectedCategory }],
  });

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setSearchQuery(localSearchQuery);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl md:text-4xl font-bold mb-4" data-testid="text-page-title">
            전체 상품
          </h1>
          
          <form onSubmit={handleSearch} className="md:hidden mb-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="상품 검색..."
                value={localSearchQuery}
                onChange={(e) => setLocalSearchQuery(e.target.value)}
                className="pl-10"
                data-testid="input-mobile-search"
              />
            </div>
          </form>

          <div className="flex items-center gap-2 mb-4 overflow-x-auto pb-2" data-testid="category-filters">
            <Filter className="h-4 w-4 text-muted-foreground flex-shrink-0" />
            <Button
              variant={selectedCategory === null ? "default" : "outline"}
              size="sm"
              onClick={() => setSelectedCategory(null)}
              data-testid="button-category-all"
            >
              전체
            </Button>
            {categories.map((category) => (
              <Button
                key={category.id}
                variant={selectedCategory === category.id ? "default" : "outline"}
                size="sm"
                onClick={() => setSelectedCategory(category.id)}
                data-testid={`button-category-${category.id}`}
              >
                {category.name}
              </Button>
            ))}
          </div>

          {searchQuery && (
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">검색 결과:</span>
              <Badge variant="secondary" data-testid="badge-search-query">
                {searchQuery}
              </Badge>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setSearchQuery("");
                  setLocalSearchQuery("");
                }}
                data-testid="button-clear-search"
              >
                초기화
              </Button>
            </div>
          )}
        </div>

        {isLoading ? (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
            {[...Array(8)].map((_, i) => (
              <div key={i} className="aspect-square bg-muted animate-pulse rounded-lg" />
            ))}
          </div>
        ) : products.length === 0 ? (
          <div className="text-center py-16" data-testid="empty-state">
            <p className="text-lg text-muted-foreground mb-4">상품이 없습니다</p>
            {searchQuery && (
              <Button
                onClick={() => {
                  setSearchQuery("");
                  setLocalSearchQuery("");
                }}
              >
                전체 상품 보기
              </Button>
            )}
          </div>
        ) : (
          <>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6" data-testid="product-grid">
              {products.map((product) => (
                <ProductCard key={product.id} product={product} />
              ))}
            </div>
            <p className="text-center text-sm text-muted-foreground mt-8" data-testid="text-product-count">
              총 {products.length}개의 상품
            </p>
          </>
        )}
      </div>
    </div>
  );
}
