// client/src/pages/OrderDetail.tsx
import { useRoute, Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Navbar } from "@/components/Navbar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Package, Truck, CheckCircle, Clock, XCircle, ArrowLeft } from "lucide-react";
import type { Order, OrderItem, Product } from "@shared/schema";

type OrderWithItems = Order & {
  orderItems: (OrderItem & { product: Product })[];
};

const statusConfig = {
  pending_payment: { label: "입금 대기", icon: Clock, variant: "secondary" as const },
  payment_confirmed: { label: "결제 확인", icon: CheckCircle, variant: "default" as const },
  preparing: { label: "배송 준비", icon: Package, variant: "default" as const },
  shipped: { label: "배송 중", icon: Truck, variant: "default" as const },
  delivered: { label: "배송 완료", icon: CheckCircle, variant: "default" as const },
  cancelled: { label: "주문 취소", icon: XCircle, variant: "destructive" as const },
};

export default function OrderDetail() {
  const [, params] = useRoute("/order/:id");
  const orderId = params?.id;

  const { data: order, isLoading } = useQuery<OrderWithItems>({
    queryKey: ["/api/orders", orderId],
    enabled: !!orderId,
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="animate-pulse space-y-4">
            <div className="h-8 bg-muted rounded w-48" />
            <div className="h-64 bg-muted rounded" />
          </div>
        </div>
      </div>
    );
  }

  if (!order) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <Card className="text-center py-16">
            <CardContent>
              <p className="text-lg text-muted-foreground mb-4">주문을 찾을 수 없습니다</p>
              <Link href="/orders">
                <Button>주문 목록으로</Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  const statusInfo = statusConfig[order.status as keyof typeof statusConfig] || statusConfig.pending_payment;
  const StatusIcon = statusInfo.icon;

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Link href="/orders">
          <Button variant="ghost" className="mb-4" data-testid="button-back">
            <ArrowLeft className="h-4 w-4 mr-2" />
            주문 목록으로
          </Button>
        </Link>

        <div className="flex items-center justify-between mb-6">
          <h1 className="text-3xl md:text-4xl font-bold" data-testid="text-page-title">
            주문 상세
          </h1>
          <Badge variant={statusInfo.variant} className="text-base px-4 py-2" data-testid="badge-order-status">
            <StatusIcon className="h-4 w-4 mr-2" />
            {statusInfo.label}
          </Badge>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>주문 정보</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <div className="flex justify-between">
                <span className="text-muted-foreground">주문 번호:</span>
                <span className="font-medium font-mono text-sm" data-testid="text-order-id">{order.id}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">주문 일시:</span>
                <span data-testid="text-order-date">
                  {new Date(order.createdAt).toLocaleDateString('ko-KR', {
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                  })}
                </span>
              </div>
              {order.trackingNumber && (
                <div className="flex justify-between">
                  <span className="text-muted-foreground">운송장 번호:</span>
                  <span className="font-medium" data-testid="text-tracking-number">{order.trackingNumber}</span>
                </div>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>배송 정보</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <div className="flex justify-between">
                <span className="text-muted-foreground">받는 사람:</span>
                <span data-testid="text-shipping-name">{order.shippingName}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">연락처:</span>
                <span data-testid="text-shipping-phone">{order.shippingPhone}</span>
              </div>
              {order.shippingPostalCode && (
                <div className="flex justify-between">
                  <span className="text-muted-foreground">우편번호:</span>
                  <span data-testid="text-shipping-postal-code">{order.shippingPostalCode}</span>
                </div>
              )}
              <div className="flex justify-between">
                <span className="text-muted-foreground">주소:</span>
                <span className="text-right" data-testid="text-shipping-address">{order.shippingAddress}</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>주문 상품</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {order.orderItems.map((item) => (
                <div
                  key={item.id}
                  className="flex items-center gap-4 pb-4 border-b last:border-0 last:pb-0"
                  data-testid={`order-item-${item.id}`}
                >
                  <div className="w-20 h-20 bg-muted rounded overflow-hidden flex-shrink-0">
                    {item.product.imageUrl && (
                      <img
                        src={item.product.imageUrl}
                        alt={item.productName}
                        className="h-full w-full object-cover"
                      />
                    )}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium mb-1" data-testid={`text-item-name-${item.id}`}>{item.productName}</p>
                    <p className="text-sm text-muted-foreground" data-testid={`text-item-price-${item.id}`}>
                      ₩{parseInt(item.productPrice).toLocaleString()} × {item.quantity}개
                    </p>
                  </div>
                  <p className="font-medium" data-testid={`text-item-total-${item.id}`}>
                    ₩{(parseFloat(item.productPrice) * item.quantity).toLocaleString()}
                  </p>
                </div>
              ))}
              <div className="pt-4 border-t">
                <div className="flex justify-between text-xl font-bold">
                  <span>총 결제 금액:</span>
                  <span className="text-primary" data-testid="text-total-amount">
                    ₩{parseInt(order.totalAmount).toLocaleString()}
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

// client/src/pages/OrderDetail.vue
<script setup lang="ts">
import { onMounted, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useOrdersStore } from '@/stores/orders';
import OrderStatusBadge from '@/components/OrderStatusBadge.vue';
import type { OrderStatus } from '@shared/schema';

const route = useRoute();
const router = useRouter();
const ordersStore = useOrdersStore();

const order = computed(() => ordersStore.currentOrder);

onMounted(async () => {
  const id = route.params.id as string;
  await ordersStore.fetchOrder(id);
});

function goBack() {
  router.push('/orders');
}

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <!-- 로딩 -->
    <div v-if="ordersStore.loading" class="flex justify-center py-12">
      <div class="text-center">
        <div class="mb-2 text-4xl">⏳</div>
        <p class="text-muted-foreground">주문 정보를 불러오는 중...</p>
      </div>
    </div>

    <!-- 에러 -->
    <div v-else-if="ordersStore.error || !order" class="py-12">
      <div class="rounded-lg border border-destructive bg-destructive/10 p-4">
        <p class="text-destructive mb-4" data-testid="text-error">
          {{ ordersStore.error || '주문을 찾을 수 없습니다' }}
        </p>
        <button
          @click="goBack"
          class="text-sm text-primary hover:underline"
          data-testid="button-go-back"
        >
          주문 내역으로 돌아가기
        </button>
      </div>
    </div>

    <!-- 주문 상세 -->
    <div v-else>
      <!-- 뒤로가기 -->
      <button
        @click="goBack"
        class="mb-6 text-sm text-muted-foreground hover:text-foreground"
        data-testid="button-back"
      >
        ← 주문 내역으로
      </button>

      <div class="mb-6 flex items-start justify-between">
        <div>
          <h1 class="text-3xl font-bold mb-2" data-testid="text-order-id">
            주문번호: {{ order.id }}
          </h1>
          <p class="text-muted-foreground" data-testid="text-order-date">
            주문일시: {{ formatDate(order.createdAt) }}
          </p>
        </div>
        <OrderStatusBadge :status="order.status as OrderStatus" />
      </div>

      <div class="grid gap-6 lg:grid-cols-3">
        <!-- 주문 상품 -->
        <div class="space-y-4 lg:col-span-2">
          <div class="rounded-lg border bg-card p-6">
            <h2 class="mb-4 text-xl font-bold">주문 상품</h2>
            <div class="space-y-4">
              <div
                v-for="item in order.orderItems"
                :key="item.id"
                class="flex justify-between border-b pb-4 last:border-b-0"
                :data-testid="`order-item-${item.id}`"
              >
                <div>
                  <h3 class="font-medium" :data-testid="`text-item-name-${item.id}`">
                    {{ item.productName }}
                  </h3>
                  <p class="text-sm text-muted-foreground">
                    {{ parseFloat(item.productPrice).toLocaleString() }}원 × {{ item.quantity }}개
                  </p>
                </div>
                <div class="text-right">
                  <p class="font-semibold" :data-testid="`text-item-total-${item.id}`">
                    {{ (parseFloat(item.productPrice) * item.quantity).toLocaleString() }}원
                  </p>
                </div>
              </div>
            </div>
            
            <div class="mt-4 border-t pt-4 flex justify-between text-lg">
              <span class="font-bold">총 금액</span>
              <span class="font-bold text-primary" data-testid="text-total-amount">
                {{ parseFloat(order.totalAmount).toLocaleString() }}원
              </span>
            </div>
          </div>
        </div>

        <!-- 배송 정보 -->
        <div class="space-y-4 lg:col-span-1">
          <div class="rounded-lg border bg-card p-6">
            <h2 class="mb-4 text-xl font-bold">배송 정보</h2>
            <div class="space-y-3 text-sm">
              <div>
                <p class="text-muted-foreground mb-1">받는 분</p>
                <p class="font-medium" data-testid="text-shipping-name">{{ order.shippingName }}</p>
              </div>
              <div>
                <p class="text-muted-foreground mb-1">연락처</p>
                <p class="font-medium" data-testid="text-shipping-phone">{{ order.shippingPhone }}</p>
              </div>
              <div>
                <p class="text-muted-foreground mb-1">주소</p>
                <p class="font-medium" data-testid="text-shipping-address">
                  {{ order.shippingAddress }}
                </p>
                <p v-if="order.shippingPostalCode" class="text-muted-foreground mt-1">
                  우편번호: {{ order.shippingPostalCode }}
                </p>
              </div>
            </div>
          </div>

          <!-- 운송장 정보 -->
          <div v-if="order.trackingNumber" class="rounded-lg border bg-card p-6">
            <h2 class="mb-4 text-xl font-bold">배송 추적</h2>
            <div class="text-sm">
              <p class="text-muted-foreground mb-1">운송장 번호</p>
              <p class="font-medium text-lg" data-testid="text-tracking-number">
                {{ order.trackingNumber }}
              </p>
            </div>
          </div>

          <!-- 주문 상태 안내 -->
          <div class="rounded-lg bg-muted p-4 text-sm">
            <p class="font-semibold mb-2">주문 상태 안내</p>
            <ul class="space-y-1 text-muted-foreground">
              <li>• 결제 대기: 결제 확인 중</li>
              <li>• 결제 완료: 상품 준비 시작 전</li>
              <li>• 상품 준비 중: 포장 및 출고 준비</li>
              <li>• 배송 중: 택배사 배송 진행</li>
              <li>• 배송 완료: 수령 완료</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
