// client/src/components/Navbar.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useAuthStore } from '@/stores/auth';
import { useCartStore } from '@/stores/cart';
import { useRouter } from 'vue-router';

const authStore = useAuthStore();
const cartStore = useCartStore();
const router = useRouter();

const cartItemCount = computed(() => cartStore.totalItems);

async function handleLogout() {
  await authStore.logout();
  router.push('/login');
}
</script>

<template>
  <header class="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
    <div class="container mx-auto px-4">
      <div class="flex h-16 items-center justify-between">
        <!-- 로고 -->
        <router-link 
          to="/" 
          class="flex items-center gap-2 text-xl font-bold text-primary hover:opacity-80 transition-opacity"
          data-testid="link-home"
        >
          ShopHub
        </router-link>

        <!-- 네비게이션 -->
        <nav class="flex items-center gap-6">
          <router-link 
            to="/" 
            class="text-sm font-medium text-foreground/60 hover:text-foreground transition-colors"
            data-testid="link-products"
          >
            상품
          </router-link>

          <template v-if="authStore.isAuthenticated">
            <!-- 로그인된 경우 -->
            <router-link 
              to="/orders" 
              class="text-sm font-medium text-foreground/60 hover:text-foreground transition-colors"
              data-testid="link-orders"
            >
              주문내역
            </router-link>

            <router-link 
              v-if="authStore.isAdmin" 
              to="/admin" 
              class="text-sm font-medium text-foreground/60 hover:text-foreground transition-colors"
              data-testid="link-admin"
            >
              관리자
            </router-link>

            <router-link 
              to="/cart" 
              class="relative text-sm font-medium text-foreground/60 hover:text-foreground transition-colors"
              data-testid="link-cart"
            >
              장바구니
              <span 
                v-if="cartItemCount > 0" 
                class="absolute -top-2 -right-3 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-xs text-primary-foreground"
                data-testid="text-cart-count"
              >
                {{ cartItemCount }}
              </span>
            </router-link>

            <div class="flex items-center gap-2">
              <span class="text-sm text-foreground/60" data-testid="text-user-name">
                {{ authStore.user?.firstName }} {{ authStore.user?.lastName }}
              </span>
              <button
                @click="handleLogout"
                class="text-sm font-medium text-foreground/60 hover:text-foreground transition-colors"
                data-testid="button-logout"
              >
                로그아웃
              </button>
            </div>
          </template>

          <template v-else>
            <!-- 로그인 안된 경우 -->
            <router-link 
              to="/login" 
              class="text-sm font-medium text-foreground/60 hover:text-foreground transition-colors"
              data-testid="link-login"
            >
              로그인
            </router-link>
            <router-link 
              to="/signup" 
              class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
              data-testid="link-signup"
            >
              회원가입
            </router-link>
          </template>
        </nav>
      </div>
    </div>
  </header>
</template>

// client/src/components/Navbar.tsx
import { Link, useLocation } from "wouter";
import { ShoppingCart, User, Search, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/hooks/useAuth";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { CartItem } from "@shared/schema";

export function Navbar() {
  const { user, isAuthenticated, isAdmin } = useAuth();
  const [location] = useLocation();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");

  const { data: cartItems = [] } = useQuery<CartItem[]>({
    queryKey: ["/api/cart"],
    enabled: isAuthenticated,
  });

  const cartCount = cartItems.reduce((sum, item) => sum + item.quantity, 0);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      window.location.href = `/?search=${encodeURIComponent(searchQuery)}`;
    }
  };

  return (
    <header className="sticky top-0 z-50 w-full bg-background border-b">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center gap-8">
            <Link href="/">
              <a className="flex items-center gap-2" data-testid="link-home">
                <div className="text-2xl font-bold text-primary">ShopHub</div>
              </a>
            </Link>

            <form onSubmit={handleSearch} className="hidden md:flex items-center flex-1 max-w-md">
              <div className="relative w-full">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="상품 검색..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                  data-testid="input-search"
                />
              </div>
            </form>
          </div>

          <nav className="hidden md:flex items-center gap-4">
            {isAuthenticated && (
              <>
                <Link href="/orders">
                  <Button
                    variant="ghost"
                    data-testid="link-orders"
                    className={location === "/orders" ? "bg-accent" : ""}
                  >
                    주문내역
                  </Button>
                </Link>
                {isAdmin && (
                  <Link href="/admin">
                    <Button
                      variant="ghost"
                      data-testid="link-admin"
                      className={location.startsWith("/admin") ? "bg-accent" : ""}
                    >
                      관리자
                    </Button>
                  </Link>
                )}
                <Link href="/cart">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="relative"
                    data-testid="button-cart"
                  >
                    <ShoppingCart className="h-5 w-5" />
                    {cartCount > 0 && (
                      <Badge
                        className="absolute -top-1 -right-1 h-5 w-5 flex items-center justify-center p-0 text-xs"
                        data-testid="badge-cart-count"
                      >
                        {cartCount}
                      </Badge>
                    )}
                  </Button>
                </Link>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => window.location.href = "/api/logout"}
                  data-testid="button-logout"
                  title="로그아웃"
                >
                  <User className="h-5 w-5" />
                </Button>
              </>
            )}
            {!isAuthenticated && (
              <Button
                onClick={() => window.location.href = "/api/login"}
                data-testid="button-login"
              >
                로그인
              </Button>
            )}
          </nav>

          <Button
            variant="ghost"
            size="icon"
            className="md:hidden"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            data-testid="button-mobile-menu"
          >
            {mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
          </Button>
        </div>

        {mobileMenuOpen && (
          <div className="md:hidden py-4 border-t">
            <form onSubmit={handleSearch} className="mb-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="상품 검색..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </form>
            <div className="flex flex-col gap-2">
              {isAuthenticated && (
                <>
                  <Link href="/orders">
                    <Button
                      variant="ghost"
                      className="w-full justify-start"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      주문내역
                    </Button>
                  </Link>
                  {isAdmin && (
                    <Link href="/admin">
                      <Button
                        variant="ghost"
                        className="w-full justify-start"
                        onClick={() => setMobileMenuOpen(false)}
                      >
                        관리자
                      </Button>
                    </Link>
                  )}
                  <Link href="/cart">
                    <Button
                      variant="ghost"
                      className="w-full justify-start"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      장바구니 ({cartCount})
                    </Button>
                  </Link>
                  <Button
                    variant="ghost"
                    className="w-full justify-start"
                    onClick={() => window.location.href = "/api/logout"}
                  >
                    로그아웃
                  </Button>
                </>
              )}
              {!isAuthenticated && (
                <Button
                  className="w-full"
                  onClick={() => window.location.href = "/api/login"}
                >
                  로그인
                </Button>
              )}
            </div>
          </div>
        )}
      </div>
    </header>
  );
}
